# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DID', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorer',
            name='password',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
