# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DID', '0005_auto_20170810_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='clas',
            name='day_total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clas',
            name='month_total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clas',
            name='semister_total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clas',
            name='week_total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
