# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DID', '0007_clas_register_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
