# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DID', '0008_record_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='weeky',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
