# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DID', '0009_subject_weeky'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='reason',
            field=models.TextField(null=True),
        ),
    ]
