# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DID', '0011_auto_20170907_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='score',
            field=models.FloatField(),
        ),
    ]
