# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-20 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DID', '0015_auto_20171220_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
