# Generated by Django 2.0.5 on 2018-05-16 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DID', '0016_auto_20171220_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='clas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DID.Clas'),
        ),
        migrations.AlterField(
            model_name='record',
            name='scorer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DID.Scorer'),
        ),
        migrations.AlterField(
            model_name='record',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DID.Subject'),
        ),
    ]
